# .github/workflows/release.yml

on:
  push:
    branches:
      - release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Package
        id: package
        run: |
          unzip ${{ steps.compile.outputs.BUILT_ARCHIVE }} -d dist/
          mkdir -p dist/user/characters/
          mkdir -p dist/user/printables/
          cp -r data/ dist/
          zip -9r archive.zip dist/
          path="$(pwd)/archive.zip"
          echo "BUILT_ARCHIVE=archive.zip" >> "$GITHUB_OUTPUT"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            ${{ steps.package.outputs.BUILT_ARCHIVE }}